### ISSUE TITLE
Move this repo to Icy organization

### ISSUE THREAD

**Issue by oeway** [bioimage-io/icy-bioimage-io#3]
see the discussion here: https://github.com/bioimage-io/collection-bioimage-io/pull/543#issuecomment-1450373591

**Comment by carlosuc3m** [comment]
Solved wiht commit https://github.com/bioimage-io/collection-bioimage-io/commit/a963da37b0bb162a66c6bb34943ab2529ab51a46
and repo https://github.com/Icy-imaging/icy-bioimage-io.
This repo can be closed once the webpage is updated
